server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: <git spring config server repository url>
          default-label: <git specific branch>
          username: <git username>
          password: <git token>
